services:
  - type: web
    name: tecnic-vn
    env: node
    plan: free
    region: singapore # hoặc oregon / frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
    domains:
      - tecnic.vn
      - www.tecnic.vn
